vich_uploader:
    db_driver: orm
    metadata:
        type: attribute
    mappings:
        photo:
            uri_prefix: /photos
            upload_destination: '%kernel.project_dir%/public/photos'
            # Will rename uploaded files using a uniqueid as a prefix.
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
